apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-insight
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis-insight
  template:
    metadata:
      labels:
        app: redis-insight
    spec:
      containers:
        - name: redis-insight
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5540
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
