apiVersion: v1
kind: Service
metadata:
  name: redis-insight
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8001
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: redis-insight
