apiVersion: v1
kind: Service
metadata:
  name: redisinsight-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5540
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: redis-insight
